clock:
    ts_start: 2024-01-01 00:00:00
    time_step_min: 15
agent:
    eat_fill_rate: 48
    eat_eff_in: 0.15
    eat_eff_out: 0.1
    sleep_fill_rate: 64
    sleep_eff_in: 0.12
    sleep_eff_out: 0.78
    relax_fill_rate: 86
    relax_eff_in: 0.0
    relax_eff_out: 0.4
    bored_thresh: 0.16