clock:
    ts_start: 2024-01-01 00:00:00
    time_step_min: 15
agent:
    eat_fill_rate: 5
    eat_eff_in: 0.75
    eat_eff_out: 0.85
    sleep_fill_rate: 8.6
    sleep_eff_in: 0.36
    sleep_eff_out: 0.33
    relax_fill_rate: 255
    relax_eff_in: 1.68
    relax_eff_out: 0.0.467
    bored_thresh: 0.46