clock:
    ts_start: 2024-01-01 00:00:00
    time_step_min: 15
agent:
    eat_fill_rate: 50
    eat_factor: 1
    eat_eff_in: 0
    eat_eff_out: 0
    sleep_fill_rate: 10
    sleep_factor_day: 1
    sleep_factor_night: 1
    sleep_eff_in: 0.2
    sleep_eff_out: 0.4
    relax_fill_rate: 20
    relax_factor: 1
    relax_eff_in: 0
    relax_eff_out: 0
    bored_thresh: 0.2